<?php
/**
 *
 *  PHP version 7
 * @author      Webjump Core Team <dev@webjump.com.br>
 * @copyright   2021 Webjump (http://www.webjump.com.br)
 * @license     http://www.webjump.com.br  Copyright
 *
 * @link        http://www.webjump.com.br
 */
declare(strict_types=1);

namespace Trilha\Pet\Block\Adminhtml\Pet\Edit;

use Magento\Backend\Block\Widget\Context;

abstract class GenericButton
{
    private Context $context;

    public function __construct(
        Context $context
    )
    {
        $this->context = $context;
    }

    public function getModelId(): ?string
    {
        return $this->context->getRequest()->getParam('entity_id');
    }

    public function getUrl($route ='', $params = []): string
    {
        $this->context->getUrlBuilder()->getUrl($route, $params);
    }
}
